# themes from https://github.com/alacritty/alacritty-theme
general.import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[font]
size = 17

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
decorations = "none"
startup_mode = "Maximized"

[window.padding]
x = 7
y = 0
